# Generated by Django 4.1.6 on 2023-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=100)),
                ('Industry_aggregation_NZSIOC', models.CharField(max_length=200)),
                ('Industry_code_NZSIOC', models.IntegerField()),
                ('Industry_name_NZSIOC', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
            ],
        ),
    ]
